// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lZgcsZC01_x-mpi_7SUwNHEPSdCm5nQ',
    appId: '1:123998902824:web:24a52c36de41ba6929331d',
    messagingSenderId: '123998902824',
    projectId: 'kuber-eec8f',
    authDomain: 'kuber-eec8f.firebaseapp.com',
    storageBucket: 'kuber-eec8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-XpcQViA_VNOHdFmskSrjHErAssQx0b8',
    appId: '1:123998902824:android:25b72a8b8d6d08bc29331d',
    messagingSenderId: '123998902824',
    projectId: 'kuber-eec8f',
    storageBucket: 'kuber-eec8f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6lZgcsZC01_x-mpi_7SUwNHEPSdCm5nQ',
    appId: '1:123998902824:web:200b01bb970f93df29331d',
    messagingSenderId: '123998902824',
    projectId: 'kuber-eec8f',
    authDomain: 'kuber-eec8f.firebaseapp.com',
    storageBucket: 'kuber-eec8f.firebasestorage.app',
  );
}
