name: kuber
description: An AI-driven FinTech app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.0.0
  fl_chart: ^0.66.0
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  provider: ^6.0.0
  shared_preferences: ^2.5.5
  share_plus: ^12.0.2
  pdf: ^3.12.0
  path_provider: ^2.1.5
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# --- ADD THIS CONFIGURATION BLOCK ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"